sudo: false
language: python 
python:
    - "2.7"

before_script:
    make install

script:
    make test

deploy:
    skip_cleanup: true
    provider: script
    script: scripts/deploy.sh
    on:
        branch: python_rewrite
