sudo: false
language: python 
python:
    - "2.7"

before_script:
    openssl aes-256-cbc -K $encrypted_e89f5256abf1_key -iv $encrypted_e89f5256abf1_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d
    make install

script:
    make test

deploy:
    skip_cleanup: true
    provider: script
    script: scripts/deploy.sh
    on:
        branch: python_rewrite
