sudo: false
language: python 
python:
    - "2.7"

before_install:
    - sed -i '/Scrapy/d' requirements.txt
    - cat requirements.txt

before_script:
    - openssl aes-256-cbc -K $encrypted_2d442f3bcb2f_key -iv $encrypted_2d442f3bcb2f_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d
    - chmod 600 scripts/id_rsa
    - make install

script:
    make test

deploy:
    skip_cleanup: true
    provider: script
    script: scripts/deploy.sh 
    on:
        branch: master 
